query getProductsCount(
  $slug: [String]
  $productTag: [String]
  $minPrice: Float
  $maxPrice: Float
  $onSale: Boolean
  $search: String
  $attributes: ProductAttributeQueryInput
  $first: Int = 1000
) {
  products(
    first: $first
    where: {
      categoryIn: $slug
      tagIn: $productTag
      visibility: VISIBLE
      minPrice: $minPrice
      maxPrice: $maxPrice
      onSale: $onSale
      search: $search
      attributes: $attributes
      status: "publish"
    }
  ) {
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    edges {
      cursor
    }
  }
}
