query getProductsByIds($ids: [Int]) {
  products(where: { include: $ids }, first: 12) {
    nodes {
      databaseId
      id
      name
      slug
      type
      averageRating
      reviewCount
      shortDescription
      ...Terms
      ...ProductCategories
      ...ProductWithAttributes
      ...PwbBrands
      ...SimpleProduct
      ...VariableProduct
      ...ExternalProduct
    }
  }
}
